export const SET_REQUEST_GLOBAL_LOADER = 'SET_REQUEST_GLOBAL_LOADER';
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SET_PARAMS = 'SET_PARAMS';
export const SET_TREE = 'SET_TREE';

export const SET_AUTH_USER = 'SET_AUTH_USER';
export const SET_AUTH_USER_SUCCESS = 'SET_AUTH_USER_SUCCESS';
export const SET_AUTH_USER_FAILURE = 'SET_AUTH_USER_FAILURE';
export const CLEAR_AUTH_USER = 'CLEAR_AUTH_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const FILTER_PATIENTS_SEARCH = 'FILTER_PATIENTS_SEARCH';
